<style type="text/css">
	#ordenes{
		
	}
	#ordenes th{
		font-size: 22px;
	}
	#ordenes td{
		font-size: 20px;
	}
	#total {
		margin-left:39%;	
		color:red;
		text-align:center;
		font-size: 20px;
	
	}
	.lineastabla1{
		background: white;
	}
	.lineastabla0{
		background: CFF;
	}
</style>
<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
		data = <?php echo $this->json?>;

				//$('#tipo option:selected')[0].value
		var tds ="";
		var total = 0;
		for(i=0; i< data.length; i++){
			tds += '<tr class="lineastabla'+i%2+'">';
			tds += '<td>'+data[i][0]+'</td>';
			tds += '<td>'+data[i][5]+'</td>';
			tds += '<td>'+data[i][2]+'</td>';
			tds += '<td>'+data[i][3]+'</td>';
			tds += '<td>'+data[i][4]+'</td>';
			total +=parseInt(data[i][4]);
		}
		$("#ordenes").append(tds);
		$("#total").text('Total: '+total+' Bsf');


	} );
</script>
<table id="ordenes" align="center" cellpadding="0" cellspacing="0">
		<tr>
			<th width="150px">Orden Andrew</th>
			<th width="150px">Orden Externa</th>
			<th width="150px">Fecha Llegada</th>
			<th width="150px">Fecha Salida</th>
			<th width="150px">Precio Subtotal</th>
		</tr>
</table>
<hr>
<p id="total"></p>
