<style type="text/css">
	#mercancia{
		border: 1px solid #FFF;
	}
	#total {
		float:right;
		margin-right:60px;	
		color:red;
	
	}
	#tabla1{
		border: 1px solid #333;
	}
</style>

<script type="text/javascript" >
	productos = <?php echo $this->prod; ?>;
	total = 0;
$(document).ready(function() {
	for(i=0; i<productos.length; i++)
		$('#producto').append('<option value="'+i+'">'+productos[i][1]+' | '+productos[i][3]+' Bsf</option>');
	for(i=1; i<=10; i++)
		$('#cantidad').append('<option value='+i+'>'+i+'</option>');

	$("#crear").click(function() {
		//$('#tipo option:selected')[0].value
		var tds = '<tr>';
		tds += '<td>'+$('#cantidad option:selected')[0].text+'</td>';
		tds += '<td>'+$('#producto option:selected')[0].text.split(' | ')[0];
		tds += '<td>'+productos[$('#producto option:selected')[0].value][3]+' Bsf</td>';
		tds += '<td>'+$('#cantidad option:selected')[0].text*productos[$('#producto option:selected')[0].value][3]+' Bsf</td>';
		tds += '</tr>';
		tds += '<tr><td colspan="5"><hr></td><tr>';
		total +=$('#cantidad option:selected')[0].text*productos[$('#producto option:selected')[0].value][3];
		$("#mercancia").append(tds);
		$("#total").text('Total: '+total+' Bsf');

		//***seteo ls info de la orden en los campos	
		
		aux=$("#productos_lavanderiaid").attr("value");
		$("#productos_lavanderiaid").attr("value",aux+","+productos[$('#producto option:selected')[0].value][0]);
		
		aux=$("#cantidades").attr("value");
		$("#cantidades").attr("value",aux+","+$('#cantidad option:selected')[0].value);
		
		$("#montototal").attr("value",total);
		
	});

});
</script>


<table align="center" id="tabla1">
	<tr>
		<td><label>Cantidad<label></td> <td><select id="cantidad"></select></td>
	</tr>
	<tr>
		<td><label>Producto<label></td> <td><select id="producto"></select></td>
	</tr>
	<tr>
		<td></td><td><button id="crear">Agregar a la orden</button></td>
	</tr>
	<tr>
		<td colspan="2" height="50px"></td>
	</tr>
	<tr>
		<td colspan="2">
			<table id="mercancia">
				<tr>
					<td width="100px">Cantidad</td>
					<td width="100px">Tipo</td>
					<td width="100px">Precio c/u</td>
					<td width="100px">Precio Subtotal</td>
				</tr>
			</table>
			
		</td>
	</tr>
	<tr>
		<td></td><td><p id="total"><p></td>
	</tr>
</table>
