<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework</title>
</head>
<body>
  <h1>Un error a ocurrido</h1>
  <h2 align="center"><?php echo $this->message ?></h2>
  <?php
   if($this->infor == '404'){
   ?>
   	<center>
  	 	  <img src="../../public/img/404web1.png" alt="" />
   	</center>
   <?php
   	}else{
   ?>
      <center>
  	 	  <img src="../../public/img/404web2.jpg" alt="" />
   	</center>
   
   <?php
   	}
   ?>
  <?php if (isset($this->exception)): ?>
  
  <h3>Informacion de la excepcion:</h3>
  <p>
      <b>Mensaje:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Parametros Requeridos:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>

</body>
</html>
